### ISSUE TITLE
Delayed expected state/validation

### ISSUE THREAD

**Issue by dannytsang** [amitfin/retry#104]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/amitfin/retry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I have an Ecoflow which has flakey WiFi. When you use a service or UI to change settings such as charge rate, the value takes hold for a short time but reverts back to the previous value because the connection failed.

### Describe the solution you'd like

An ability to delay the expected state or validation parameter to cater for the above scenario. For example, allowing an expected state check to occur 30 seconds after the initial service call should work.

### Describe alternatives you've considered

None.

### Additional context

I believe what I am seeing from Ecoflow is Home Assistant takes the changes as the current state but when the cloud integration updates (not sure if this is push or pull), it will revert to the actual state of the setting.

**Comment by amitfin** [comment]
[v2.12.0](https://github.com/amitfin/retry/releases/tag/v2.12.0) adds a new `state_delay` parameter. Documentation can be found [here](https://github.com/amitfin/retry?tab=readme-ov-file#state_delay-parameter-optional).

@dannytsang  , please let me know if it's working and addressing your needs.

**Comment by dannytsang** [comment]
Ah brill. I'll report back soon.

**Comment by dannytsang** [comment]
@amitfin I'm getting an extra keys not allowed error when I use state_delay. I checked the automation and I think it's right. Can you see if there's anything wrong?

![image](https://github.com/user-attachments/assets/d78d596e-33f8-42b6-8c2b-0b42ef6177f1)

**Comment by amitfin** [comment]
@dannytsang did you upgrade to v2.12.0? It requires a reboot.

**Comment by dannytsang** [comment]
@amitfin i was not! That's annoying considering other HACS integration had updates between 28th and now. I have updated and restarted. I will hopefully test it in the next couple of days.

Thanks again.

**Comment by dannytsang** [comment]
Worked great and even got the failed notification. Thanks @amitfin
