### ISSUE TITLE
Control repair ticket per-invocation

### ISSUE THREAD

**Issue by gdgib** [amitfin/retry#136]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/amitfin/retry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Retry either creates repairs for all failures or none, depending on the configuration setting.  I'd love some finer grain control.

### Describe the solution you'd like

Some options:

1. Disable repair creation when `on_error` is specified even if it's globally enabled.  Since the user is obviously handling the situation in the script/automation, the repair seems redundant.  I don't LOVE this option.
2. Add a 'repair' boolean to 'data' so each call to retry can manually specify whether to create a repair or not.  If this is specified, it should override the global setting.  If this is not specified the global setting should be used to determine whether to create a repair.

### Describe alternatives you've considered

I guess I could disable repairs globally and add them back in `on_error` when I want them, but this seems a bit clumsy.

### Additional context

There are several places where I'd like to retry an action, but failures are transient and rendered irrelevant after a few minutes.  Don't get me wrong, I'll keep an eye on the logs for this, but the repairs are just noise.  Then there are places where a retry failure is a Very Bad Thing(tm), and I really want the visible repair.

**Comment by gdgib** [comment]
@amitfin if you're amenable to this, I wouldn't mind opening a PR in a day or two.  Just oddly busy today and tomorrow, and I wanted to get your opinion of the feature before I code something pointless (in case there's a better way or you have something else in mind).

**Comment by amitfin** [comment]
[v3.1.0](https://github.com/amitfin/retry/releases/tag/v3.1.0) adds a `repair` parameter (documentation is [here](https://github.com/amitfin/retry?tab=readme-ov-file#repair-parameter-optional)).
@gdgib , please comment if it addresses the use case.

**Comment by gdgib** [comment]
I wasn't expecting you to not only like the idea but implement it so fast I didn't even have time to comment.  I sincerely appreciate it.  Not only does that address the use case, it is exactly what I was thinking.  Thank you very much @amitfin.  I am impressed and grateful.
