### ISSUE TITLE
I'm not seeing the GUI elements for retry.actions

### ISSUE THREAD

**Issue by Jeroen2000** [amitfin/retry#139]
## System Information

version | core-2024.10.3
-- | --
installation_type | Unsupported Third Party Container
dev | false
hassio | false
docker | true
user | abc
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.51+rpt-rpi-2712
arch | aarch64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4982
Installed Version | 2.0.1
Stage | running
Available Repositories | 1476
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 8, 2024 at 7:38 AM
-- | --
current_recorder_run | December 9, 2024 at 11:06 PM
estimated_db_size | 852.39 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/amitfin/retry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Maybe I'm being a bit daft but:
I'm not seeing the GUI elements "retries", "backoff", "expected state", "validation", "State Delay Period", when selecting 
Retry: Actions
### Reproduction steps

1. Go to Settings > Automations & scenes
2. Open an existing automation or create a new one
3. Scroll down to the "Then do" section, click on "ADD ACTION"
4. In the "Search action" box choose "Retry: Actions"
5. Click on the "Inner" "ADD ACTION button". Not the one directly below it (which would be the outer one)
6. Click on "Device".  I selected an Ikea smart plug. At this point I would expect the aforementioned GUI elements to show up. See picture.
<img width="690" alt="Screenshot 2024-12-09 at 23 36 39" src="https://github.com/user-attachments/assets/baf411cb-9d3a-4a0a-959c-ecb88b36ef9e">

### Debug logs

```text
I did not get this to work immediately. If very important I will try again with a fresh mind:-)
```

**Comment by amitfin** [comment]
Most of the fields where hidden for non-advanced users.
[v3.2.0](https://github.com/amitfin/retry/releases/tag/v3.2.0) fixed that:

> The `advanced` property was set to True for most fields. It makes the field hidden in the UI for non-advanced users (a profile option which can be configured [here](https://my.home-assistant.io/redirect/profile)). The `advanced` property was removed and the default is False. This means that all fields are available for all users.
