### ISSUE TITLE
Expected state could be an array

### ISSUE THREAD

**Issue by matwojcik** [amitfin/retry#17]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/amitfin/retry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Certain devices have state in between from off to on. An example is a curtain which state travels from closed -> opening -> open. State changing into opening indicates that the device has successfully received an open action. In the result there is no more need to trigger open action again.

### Describe the solution you'd like

I thought that `expected_state` could be an array of states, which would contain both `opening`, `open`, so on either of those statues the retry action could be considered successful. 

### Describe alternatives you've considered

An alternative would be having expected state equal `opening`, but it would exclude cases when the device reports only end state.

### Additional context

-

**Comment by amitfin** [comment]
Done.
Requires [v2.3.0](https://github.com/amitfin/retry/releases/tag/v2.3.0).
