### ISSUE TITLE
Reliable Telegram Bot with Retry

### ISSUE THREAD

**Issue by StefanoGiu** [amitfin/retry#24]
### System Health details

I'm trying to make a reliable telegram bot using retry to send the message again in case of error.

I tried with:
                    service: retry.call
                    target:
                      entity_id: telegram_bot.send_message
                    data:
                      service: telegram_bot.send_message
                      title: >-
                                --{{title}}--
                      message: >-
                                {{message}}

But I got the error homeassistant.exceptions.InvalidStateError: telegram_bot.send_message is not available and the message is sent successfully 7 times each time, cause it doesn't recognize the success for it.

I also tried with:
                 - service: retry.call
                   data:
                      service: notify.{{notifier}}
                      title: >-
                            {{title}}
                      message: >-
                            {{message}}

But in this case, it doesn't retry it in case of error. 

Any suggestion?

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/amitfin/retry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Described above

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
homeassistant.exceptions.InvalidStateError: telegram_bot.send_message is not available
```

**Comment by amitfin** [comment]
Can you try removing?
```
target:
  entity_id: telegram_bot.send_message
```

`telegram_bot.send_message` is not an entity. It's a service.

**Comment by StefanoGiu** [comment]
Removing it solves the exeption in the log, but still the retry is not able to re-submit telegram messages that are in error.

I have bunch of those errors if I try to issue 100 message on telegram in 1 second (a test to verify if retry works), but actually retry is not triggering any new tentative for telegram bot...

2023-09-05 13:53:55.545 WARNING (SyncWorker_21) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Connection pool is full, discarding connection: api.telegram.org
2023-09-05 13:53:55.547 ERROR (SyncWorker_22) [homeassistant.components.telegram_bot] Error sending message: Timed out. Args: (808687121, '+++ *Test Notifier*\nTest numero 96'), kwargs: {'parse_mode': 'Markdown', 'disable_web_page_preview': None, 'disable_notification': False, 'reply_to_message_id': None, 'reply_markup': None, 'timeout': None}
2023-09-05 13:53:55.553 ERROR (SyncWorker_21) [homeassistant.components.telegram_bot] Error sending message: Timed out. Args: (808687121, '+++ *Test Notifier*\nTest numero 98'), kwargs: {'parse_mode': 'Markdown', 'disable_web_page_preview': None, 'disable_notification': False, 'reply_to_message_id': None, 'reply_markup': None, 'timeout': None}
2023-09-05 13:53:55.646 WARNING (SyncWorker_49) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Connection pool is full, discarding connection: api.telegram.org
2023-09-05 13:53:55.649 ERROR (SyncWorker_49) [homeassistant.components.telegram_bot] Error sending message: Timed out. Args: (808687121, '+++ *Test Notifier*\nTest numero 99'), kwargs: {'parse_mode': 'Markdown', 'disable_web_page_preview': None, 'disable_notification': False, 'reply_to_message_id': None, 'reply_markup': None, 'timeout': None}
2023-09-05 13:53:55.677 WARNING (SyncWorker_57) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Connection pool is full, discarding connection: api.telegram.org
2023-09-05 13:53:55.680 ERROR (SyncWorker_57) [homeassistant.components.telegram_bot] Error sending message: Timed out. Args: (808687121, '+++ *Test Notifier*\nTest numero 100'), kwargs: {'parse_mode': 'Markdown', 'disable_web_page_preview': None, 'disable_notification': False, 'reply_to_message_id': None, 'reply_markup': None, 'timeout': None}

**Comment by StefanoGiu** [comment]
How can I make telegram_bot reliable with retry?

**Comment by amitfin** [comment]
The problem is [here](https://github.com/home-assistant/core/blob/582eeea08215a8e553e90c281fcfb4774788daca/homeassistant/components/telegram_bot/__init__.py#L644) (inside the `telegram_bot` integration code).
The integration doesn't propagate the error (the exception), so from the caller perspective (`retry.call`) it was successful. 
A straightforward change is to add `raise` inside the `except` block:
```
        except TelegramError as exc:
            _LOGGER.error(
                "%s: %s. Args: %s, kwargs: %s", msg_error, exc, args_msg, kwargs_msg
            )
            raise
```
But it requires coordination with the component's owner...

**Comment by StefanoGiu** [comment]
I think because the raise is inside telegram\utils\request.py

**Comment by amitfin** [comment]
Something is wrong in your test environment:
- The log error listed above is inside `_run_service_call_catch_exceptions` [here](https://github.com/home-assistant/core/blob/5afba6327c10ea65c8a5db60543846f21c019f18/homeassistant/core.py#L2006)
- `_run_service_call_catch_exceptions` is only called from [here](https://github.com/home-assistant/core/blob/5afba6327c10ea65c8a5db60543846f21c019f18/homeassistant/core.py#L1975), only when the input parameter `blocking` is `False`
- But `retry.call` sets `blocking` to `True` [here](https://github.com/amitfin/retry/blob/3c83b4e6826e474cfe20fceb8ca95c657ca0688d/custom_components/retry/__init__.py#L253)

This means that the above service call was not done by the service `retry.call`.

**Comment by StefanoGiu** [comment]
I was calling telegram_bot.send_message from a script and then calling with call.retry that script.... but I do understand that retry needs to receive the error from the caller itself and not from any sub task/sub processes, right?

I changed from:

                  - service: retry.call
                    data:
                       service: notify.{{notifier}}
                       title: >-
                             {{title}}
                       message: >-
                             {{message}}

to:

                 - service: retry.call
                   data:
                     service: telegram_bot.send_message
                     title: >-
                               {{title}}
                     message: >-
                               {{message}}

and then I modified the telegram_bot file in this way:

        senterror = False
        senterrormsg = ""
        try:
----------------------
        except TelegramError as exc:
            _LOGGER.error(
                "%s: %s. Args: %s, kwargs: %s", msg_error, exc, args_msg, kwargs_msg
            )
            senterror = True
            senterrormsg = str(msg_error)
        if senterror:
            raise TypeError(senterrormsg)

This to avoid the double exception from the caller.

Now everything seems to work properly, but the only thing is that I need the raise in the Telegram Bot and therefore I see the stack trace in the home assistant log.

Is there another way to trigger retry rather than raise ?

I'd like to keep the log clean without the stack trace. Thanks

**Comment by amitfin** [comment]
Happy to hear that things are working as expected now.

Regarding the log entries: 
There is no way to propagate errors from a service call other than throwing an exception. See also the last paragraph in [this comment](https://github.com/home-assistant/architecture/discussions/777).
You can filter out log entries as described in the [logger](https://www.home-assistant.io/integrations/logger/) documentation. It won't have any impact on `retry.call`.

**Comment by StefanoGiu** [comment]
Got it, I think now that services are responding back, this should improve.

I tested telegram bot with messages/inline keyboard/photo and video stressing the number of messages sent and now retry seems to handle them properly... :) very good package you did!!!

Is there a way to keep the sequenciality of the events? e.g. if I sent 100 messages and number 12 fails, to wait until 12 is sent properly or it's the last attempt for 12 before calling the message 13...

consider that I'm using a script with queued mechanism to queue all the messages I send via telegram bot, so I could wait for example the retry service to have done before proceeding to the next execution (e.g. retry OK or retry made the last attempt).

I hope I was clear...

**Comment by amitfin** [comment]
Thanks!

The retries are done in the background and therefore there is no indication of completion (either on success or on failure). Note that a failure happens after ~1 minute (7 retries with exponential backoff), so it's possible to wait for that amount of time (or less if a lower number of retries is provided as an input parameter).

**Comment by StefanoGiu** [comment]
Thank you... I would not want to wait if not needed (e.g. all messages are ok).... so I'll keep it as it is... order might not be respected.

Thank you for your time.
