### ISSUE TITLE
Toggle service suitable?

### ISSUE THREAD

**Issue by oudoulj** [amitfin/retry#42]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/amitfin/retry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I am wondering if
`service: homeassistant.toggle`
is a suitable service to use Retry with?
I use that service to turn on/off lights in one automation instead of having 2 of them (one for `off` and one for `on`)

### Describe the solution you'd like

I was thinking of
```
service: retry.call
data:
  service: homeassistant.toggle
target:
  entity_id: light.kitchen
```
but I'd like to be sure to, say, turn off the light and not turn it on in case the light was on and the toggle was called BUT failed and then was "retried" but this second time it would try to turn the light on (instead of off).
Hope I make sense ^^

### Describe alternatives you've considered

I don't have any.

### Additional context

No additional context.

**Comment by amitfin** [comment]
`homeassistant.toggle` is not suitable since it's a relative operation and not an absolute one.

For the [README](https://github.com/amitfin/retry/blob/main/README.md) file:

> Note: This service is not suitable for the following scenarios:
> 1. ...
> 2. For a relative state change: for example, `fan.increase_speed` is relative while `light.turn_on` is absolute. The reason is that a relative service call might change the state and only then a failure occurs. Calling it again might have an unintentional result.
> 3. ...

I'm adding `homeassistant.toggle` as another explicit example in the documentation quoted above.

**Comment by amitfin** [comment]
https://github.com/amitfin/retry/commit/5f2f3264d7fb39002f55d5f0b4bc65203f2c3f2a (the README file update)

**Comment by amitfin** [comment]
Please note that it's not needed to double the amount of automation rules in order to use absolute operations. It's possible to use [trigger ID](https://www.home-assistant.io/docs/automation/trigger/#trigger-id) with [if-then](https://www.home-assistant.io/docs/scripts/#if-then) or [choose](https://www.home-assistant.io/docs/scripts/#choose-a-group-of-actions) which can then have absolute operations based on the trigger ID.

**Comment by oudoulj** [comment]
> Please note that it's not needed to double the amount of automation rules in order to use absolute operations. It's possible to use [trigger ID](https://www.home-assistant.io/docs/automation/trigger/#trigger-id) with [if-then](https://www.home-assistant.io/docs/scripts/#if-then) or [choose](https://www.home-assistant.io/docs/scripts/#choose-a-group-of-actions) which can then have absolute operations based on the trigger ID.

Interesting approach/suggestion!
Thank you for the answer and the update of the README file :+1:
