### ISSUE TITLE
Retry Action not working

### ISSUE THREAD

**Issue by MKlitgaard2** [amitfin/retry#43]
## System Information

version | core-2023.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Europe/Copenhagen
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.33.0
Stage | running
Available Repositories | 1348
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 24 November 2024 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-14.ui.nabu.casa
certificate_status | ready
instance_id | 6efd72cb130548089d01047848900fe0
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 17.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.8.1), Mosquitto broker (6.4.0), OneDrive Backup (2.2.4), Studio Code Server (5.14.2), Silicon Labs Multiprotocol (2.3.2), Matter Server (5.0.1), Music Assistant BETA (2.0.0b78), ZigStar TI CC2652P/P7 FW Flasher (0.3.0), ZigStar Silicon Labs FW Flasher (0.1.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 9
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 11 December 2023 at 09:07
-- | --
current_recorder_run | 17 December 2023 at 13:31
estimated_db_size | 269.08 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.3 (a8c6d45)
-- | --
cloud_online | 0 / 1
local_online | 0 / 0

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.14
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/amitfin/retry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Created this retry using the visual editor

service: retry.actions
data:
  sequence:
    - device_id: d42f46a2bb476217831b399d0f22e364
      domain: cover
      entity_id: 47dc0af5b7b84c441ba39368324574ec
      type: open

Running the action throws this error:
Error running action
not a valid value for dictionary value @ data['entity_id']. Got None

This works:
device_id: d42f46a2bb476217831b399d0f22e364
domain: cover
entity_id: 47dc0af5b7b84c441ba39368324574ec
type: open

### Reproduction steps

1. create action using Visual editor
2. Select Run in the editor window

### Debug logs

```text
.
```

**Comment by amitfin** [comment]
> entity_id: 47dc0af5b7b84c441ba39368324574ec

This is not a valid `entity_id` (a valid one will look like `light.kitchen`).

**Comment by jrunestone** [comment]
I had the same issue, before realizing this only supports calling another service I guess? I can't add any other action (I was trying to turn a switch on).

**Comment by kchiem** [comment]
> Not sure how this configuration was made, but it's not a valid one. There should be no `domain` or `type` and `entity_id` is also not valid.

It was made using the Visual Editor, choosing Device -> Action.  For example:

![ScreenClip](https://github.com/user-attachments/assets/0172764d-1b57-4ace-9525-fb4ced41d1a5)

Results in this YAML:

![ScreenClip](https://github.com/user-attachments/assets/f3c99a4a-4e35-40d6-ae35-f53dbba701d4)

If this isn't supported, perhaps it should be disabled in some way so that the Visual Editor doesn't create this type of config.

**Comment by marbon87** [comment]
My workaround for the same problem was to wrap the device action in a script.
